$ANSIBLE_VAULT;1.1;AES256
62656333386233346633663037343330653864643531376136666235663863323536326335663466
6662343264633431323736316263646638303130396238300a636664386638313331353666303532
31623735646532626333336538386339663266336166643863643461313065323531663636633936
6337326333643238330a663635363239366664316266643932613532303264353563373036626237
30336263353235313230646334383336643037666664383935396630623366643965653464333338
35623633303034616464353834323364633161633161636634643536343662343636306538666161
32643835383265653737383865366666373936633932356462346435626135333866633863313339
39616635313564306163336333373439393239653064343236373534666439353630626233313063
31653635666365393432653966393966393432623137613932303463353330373734623065343434
36393530356533363364386461653534383031343765623138323262626566316261323166663033
35323266633061373634303635663538363636666666393032323566666435626438366230386636
33353065663566303934
