$ANSIBLE_VAULT;1.1;AES256
66393039633162306462303863656637636639336331343861343164356636643264373839333566
6331393534356534663964306332613335316131353335360a306436333932343134613037643138
39623861306562633661366361373163643665346433316362383835363535333330663366613636
6532656261363737610a306633646632313137343031306535373634653962303562326639383662
31636532363964313463313166346434386133653734643137393537386538333535653161383034
36393938353966396464353834633835653937643161646465646365323436326335376636333233
62343737393462626438343230303665336564656431323736303066643634623666336334353761
65626336386338323864636434323562636331633632666235306665656366336164363732363536
34343635373330393964613130356465646535343939623261363537346638656261613630316333
39356535663562653461396134666334626461323161613333653330393631313337303338626261
38326362653463343430626630653234316337626336356466386230396366316334383233396337
64373234376331653334
