$ANSIBLE_VAULT;1.1;AES256
33643861383633336334353331343866353535393333333832646362623237376238376432303732
3431663832346663336332353238666139613939373066300a326663623737376364633438353934
61386332363236656431333035363330373863663435386339356562363062373336633737313930
3333376233626432380a663038333837626665313036616362303037326235613863613666636566
30643039616336383936313166336266666630393761666439333731656230336433663630613363
34653132326133313639666134633365633735363738343636623262386361646563346164613563
64336562303939393564323564633464636230313932373933343465343631333231333831333438
62623234386563653165313961313030383837623230356531633238343737656532373033343833
64373732636633303363323132666531356139313030653666623366623630613335616233616635
38353635656231616366333131646166613532336330626432356466393431663066313433613362
62336332336231353131623031666334363332613537656366323464633866326537383538626565
38373932346534396533
