$ANSIBLE_VAULT;1.1;AES256
63393135306662363639646636326231303237353663633937383435633131616438363866356631
6135353364346266333136643630316237626230613663340a623363373434306138613234333562
63303833343365656361393463616138313032633938363934623536373561666435653261623361
6363613266323863340a393530366161626133376136623836643162303661386264373961363038
34393839396463346633353330666433363163653732396535623037343030633461316463613832
36623037633235373264346239346535346332633434643365613464636362346362383239663162
66393034356338633266343664666263386233666265626436303139663766636437323031313430
63313764363466363430396234633432356234346534633862326535613731386231363363376532
35323935383666643563396631393536633930633530313664376331663931353463663465356530
38646333643735323166623632343936626162653763363236666266643132333133346463356261
65363535326130303065356163646233333536353166313964316262326639356433653862633134
66386631366230353235
